### ISSUE TITLE
Grundlagen der Klettertechnik - fehlende Kurstermine

### ISSUE THREAD

**Issue by ChristinaSchwarzmann** [wodo/WebTool3#10]
Hier ist nur der erste Kurstermin eingetragen, es fehlen allerdings noch folgende Tage:
-17.10.
-24.10.
-31.10.
-07.11.
-14.11.
Bei der Kurszeit steht nur die Beginnzeit. Die Endzeit fehlt.

**Comment by wodo** [comment]
@ChristinaSchwarzmann Kannst Du mir bitte folgende Daten geben:

- Buchungscode
- Die Endzeit

Dann kann das Problem sofort gelöst werden.

**Comment by wodo** [comment]
Ich bin von folgendem Buchungscode ausgegangen: GKT-902
Ich habe die Zeitangaben aus dem ersten Termin übernommen.

**Comment by Gabigaebl** [comment]
Hallo Wodo,

die Endzeit für GKT-902 ist 21:30 Uhr.

Viele Grüße
Christina

Von: Wolfgang Doll <notifications@github.com>
Gesendet: Freitag, 5. Juli 2019 04:52
An: wodo/WebTool3 <WebTool3@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [wodo/WebTool3] Grundlagen der Klettertechnik - fehlende Kurstermine (#10)


@ChristinaSchwarzmann<https://github.com/ChristinaSchwarzmann> Kannst Du mir bitte folgende Daten geben:

  *   Buchungscode
  *   Die Endzeit

Dann kann das Problem sofort gelöst werden.
